# Generated by Django 4.2.11 on 2024-04-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstNM', models.CharField(max_length=20)),
                ('secondNM', models.CharField(max_length=20)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
    ]
