# Generated by Django 4.2.11 on 2024-04-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('firstNM', models.CharField(max_length=20)),
                ('secondNM', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=40)),
                ('userRole', models.CharField(max_length=40)),
            ],
        ),
    ]
