# Generated by Django 4.2.11 on 2024-04-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_user_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userRole',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
