# Generated by Django 4.2.11 on 2024-04-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_user_firstnm_alter_user_secondnm'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photoLink', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('date', models.CharField(blank=True, max_length=1024)),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('userId', models.IntegerField(default=0)),
                ('photoLink', models.CharField(max_length=255)),
                ('speed', models.CharField(blank=True, max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('articleNumber', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('flightTime', models.IntegerField(default=0)),
                ('range', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('maxWind', models.IntegerField(default=0)),
                ('maxAltitude', models.IntegerField(default=0)),
                ('minAltitude', models.IntegerField(default=0)),
                ('motorsNumber', models.IntegerField(default=0)),
            ],
        ),
    ]
