# Generated by Django 4.2.11 on 2024-04-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_news_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstUserId', models.IntegerField(default=0)),
                ('secondUserId', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('chatName', models.CharField(blank=True, max_length=40)),
                ('firstUserName', models.CharField(blank=True, max_length=40)),
                ('secondUserName', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1024)),
                ('date', models.CharField(blank=True, max_length=40)),
                ('chatId', models.IntegerField(default=0)),
                ('userId', models.IntegerField(default=0)),
            ],
        ),
    ]
