# Generated by Django 4.2.11 on 2024-04-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_chat_massage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Massage',
            new_name='Message',
        ),
    ]
